services:
  - type: web
    name: students-enrollment-api
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    healthCheckPath: /students

staticSites:
  - name: students-enrollment-frontend
    rootDir: client/students-enrollment-course
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: students-enrollment-api
          property: url

